// Generates css/edges.css: static clip-path edge cuts for the four half-faces.
// Sawtooth top (~4px pitch), ragged bottom (0–3px). Deterministic seed so every build matches.
// The DC's verbatim polygons were not handed off; these follow the spec's dimensions instead.
import { writeFileSync } from 'node:fs';
const W = 430, H = 290;
let seed = 20260901; const rnd = () => { seed = (seed * 1103515245 + 12345) & 0x7fffffff; return seed / 0x7fffffff; };
const pts = [];
// top sawtooth: (0,4),(2,0),(4,4)...
const top = []; for (let x = 0; x <= W; x += 2) top.push([x, (x / 2) % 2 === 0 ? 4 : 0]);
top.push([W, H], [0, H]);
// bottom ragged: (0,0),(W,0), then right→left along the bottom
const bottom = [[0, 0], [W, 0]]; for (let x = W; x >= 0; x -= 6) bottom.push([x, H - Math.round(rnd() * 3 * 10) / 10]);
const poly = (p, mirror) => 'polygon(' + p.map(([x, y]) => `${mirror ? (W - x) : x}px ${y}px`).join(',') + ')';
const css = `/* generated by tools/make-edges.mjs — do not edit by hand */
.half.top .face.front { clip-path: ${poly(top, false)}; }
.half.top .face.back { clip-path: ${poly(top, true)}; }
.half.bottom .face.front { clip-path: ${poly(bottom, false)}; }
.half.bottom .face.back { clip-path: ${poly(bottom, true)}; }
`;
writeFileSync('css/edges.css', css); console.log('wrote css/edges.css', css.length, 'bytes');
